#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

openapi: 3.0.0
info:
  title: iotdb-collector-rest
  description: IoTDB Rest API for Collector
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://127.0.0.1:17070/
    description: api
security:
  - basic: []
paths:
  /admin/v1/createPipe:
    post:
      summary: createPipe
      description: createPipe
      operationId: createPipe
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePipeRequest'
      responses:
        "200":
          description: ExecutionStatus
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionStatus'

  /admin/v1/alterPipe:
    post:
      summary: alterPipe
      description: alterPipe
      operationId: alterPipe
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlterPipeRequest'
      responses:
        "200":
          description: ExecutionStatus
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionStatus'

  /admin/v1/startPipe:
    post:
      summary: startPipe
      description: startPipe
      operationId: startPipe
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartPipeRequest'
      responses:
        "200":
          description: ExecutionStatus
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionStatus'

  /admin/v1/stopPipe:
    post:
      summary: stopPipe
      description: stopPipe
      operationId: stopPipe
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StopPipeRequest'
      responses:
        "200":
          description: ExecutionStatus
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionStatus'

  /admin/v1/dropPipe:
    post:
      summary: dropPipe
      description: dropPipe
      operationId: dropPipe
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DropPipeRequest'
      responses:
        "200":
          description: ExecutionStatus
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionStatus'

components:
  schemas:
    CreatePipeRequest:
      title: CreatePipeRequest
      type: object
      properties:
        sourceAttribute:
          type: object
          additionalProperties:
            type: string
        processorAttribute:
          type: object
          additionalProperties:
            type: string
        sinkAttribute:
          type: object
          additionalProperties:
            type: string
        taskId:
          type: string


    AlterPipeRequest:
      title: AlterPipeRequest
      type: object
      properties:
        timestamps:
          type: array
          items:
            type: integer
            format: int64
        measurements:
          type: array
          items:
            type: string
        dataTypes:
          type: array
          items:
            type: string
        values:
          type: array
          items:
            type: array
            items:
              type: object
        isAligned:
          type: boolean
        deviceId:
          type: string

    StartPipeRequest:
      title: StartPipeRequest
      type: object
      properties:
        timestamps:
          type: array
          items:
            type: integer
            format: int64
        measurements:
          type: array
          items:
            type: string
        dataTypes:
          type: array
          items:
            type: string
        values:
          type: array
          items:
            type: array
            items:
              type: object
        isAligned:
          type: boolean
        deviceId:
          type: string

    StopPipeRequest:
      title: StopPipeRequest
      type: object
      properties:
        taskId:
          type: string

    DropPipeRequest:
      title: DropPipeRequest
      type: object
      properties:
        timestamps:
          type: array
          items:
            type: integer
            format: int64
        measurements:
          type: array
          items:
            type: string
        dataTypes:
          type: array
          items:
            type: string
        values:
          type: array
          items:
            type: array
            items:
              type: object
        isAligned:
          type: boolean
        deviceId:
          type: string

    ExecutionStatus:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

  securitySchemes:
    basic:
      type: http
      scheme: basic
    APIKey:
      type: apiKey
      name: API Key
      in: header
