#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-scrape
  namespace: default
  labels:
    app.kubernetes.io/name: metric-scrape
    app.kubernetes.io/part-of: iotdb-monitoring
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: metric-scrape
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metric-scrape
        app.kubernetes.io/part-of: iotdb-monitoring
      annotations:
        configmap/checksum: "v1"
    spec:
      containers:
        - name: metric-scrape
          image: metric-scrape:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi
          volumeMounts:
            - mountPath: /app/conf
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: metric-scrape-config
            items:
              - key: metric-scrape.yml
                path: metric-scrape.yml
