#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

openapi: 3.0.0
info:
  title: iotdb-collector-rest
  description: IoTDB Rest API for Collector
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://127.0.0.1:17070/
    description: api
paths:
  /plugin/v1/create:
    post:
      operationId: createPlugin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePluginRequest'
      responses:
        "200":
          $ref: '#/components/responses/SuccessExecutionStatus'

  /plugin/v1/drop:
    post:
      operationId: dropPlugin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DropPluginRequest'
      responses:
        "200":
          $ref: '#/components/responses/SuccessExecutionStatus'

  /plugin/v1/show:
    post:
      operationId: showPlugin
      responses:
        "200":
          $ref: '#/components/responses/SuccessExecutionStatus'

components:
  schemas:
    CreatePluginRequest:
      properties:
        pluginName:
          type: string
        className:
          type: string
        jarName:
          type: string

    DropPluginRequest:
      properties:
        pluginName:
          type: string

    ExecutionStatus:
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  responses:
    SuccessExecutionStatus:
      description: ExecutionStatus
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExecutionStatus'